### PR TITLE
Feature: Use afl instrumented binaries

### PR DESCRIPTION
**Pull request by ekilmer**
I thought it would be nice to have the option to use instrumented binaries during the fuzzing portion to speed it up.

### CODE REVIEW

**Comment by ekilmer** [comment]
Actually, I just thought of something: Is the bitmap generated from an instrumented binary still valid for a non-instrumented binary for drilling/tracing? I think I'll need to read the AFL documentation and how the bitmap is created.

**Comment by ekilmer** [comment]
This looks like the most relevant section in the [documentation](http://lcamtuf.coredump.cx/afl/technical_details.txt), and it doesn't look like the injected instrumentation will affect the bitmap values since the bitmap relies on branch transitions and the injected code doesn't use any branching.
```
1) Coverage measurements
------------------------

The instrumentation injected into compiled programs captures branch (edge)
coverage, along with coarse branch-taken hit counts. The code injected at
branch points is essentially equivalent to:

  cur_location = <COMPILE_TIME_RANDOM>;
  shared_mem[cur_location ^ prev_location]++; 
  prev_location = cur_location >> 1;
```
and here is the description of the bitmap (`shared_mem[]`)
```
The shared_mem[] array is a 64 kB SHM region passed to the instrumented binary
by the caller. Every byte set in the output map can be thought of as a hit for
a particular (branch_src, branch_dst) tuple in the instrumented code.
```

**Comment by salls** [comment]
The bitmap from an instrumented binary will not match up with Driller. It might be possible with changes to Driller, although I'm not sure how much work it would be. 

Afl instrumentation generates the bitmap using random numbers rather than addresses like it does during qemu. In afl-as.c you'll see code like:
```

**Comment by ekilmer** [comment]
Okay, I'll close this then. Maybe in the future I can look into it. Thank you!

**Pull request closed without merging**
