### PR TITLE
Don't explore angr internals

### PR DESCRIPTION
**Pull request by Owlz**
Adding check so that we don't spend time exploring transition changes in angr internals.

#6

### CODE REVIEW

**Comment by salls** [comment]
I think that this also needs a check that this is not None:
branches.missed[0]._project.loader.addr_belongs_to_object(path.addr)
Dynamically allocated code could return cause this to not return an actual object

**Comment by ButtonYe** [comment]
I'm wonder where I can get CGC tests.

**Comment by zardus** [comment]
Hey guys, what's the status of this PR?

**Comment by salls** [comment]
Looking at this again it looks correct. I'll merge it

**Pull request merged**
