### PR TITLE
Fix the size of the default bitmap

### PR DESCRIPTION
**Pull request by benquike**
It should be 2^16.

### CODE REVIEW

**Comment by benquike** [comment]
And one more comment:

https://github.com/shellphish/driller/blob/master/driller/driller.py#L172
In think this line is problematic.

```
hit = bool(ord(self.fuzz_bitmap[cur_loc ^ prev_loc]) ^ 0xff)
```

It should be:

```
hit = bool(~ ord(self.fuzz_bitmap[cur_loc ^ prev_loc]) ^ 0xff)
```

**Comment by zardus** [comment]
@NickStephens, @salls, or @jacopo, what do you guys think about that last comment (and, while you're at it, the changes so far)? I'm not very familiar with the exact hash calculation...

**Comment by salls** [comment]
I agree the fuzz bitmap should be size 2^16. 

I don't think `hit` calculation needs the bitwise not. If the bitmap is all "\xff" then the current calculation results in `hit` being false, indicating we have not already seen that transition.

**Comment by zardus** [comment]
Cool. I've merged the 2^16 size, then. Thanks, @benquike!

**Comment by benquike** [comment]
If the bitmap is `\xff`, we should consider it as not seen.

If you look at the implementation of AFL, it uses the bitmap exactly in this way:
https://hexdump.cs.purdue.edu/source/xref/afl/afl-fuzz.c#has_new_bits

**Comment by salls** [comment]
Isn't that what we do? If the bitmap is \xff then hit is false, meaning that we haven't seen that transition

**Comment by benquike** [comment]
Really?

what is \xff & \xff evaluated to?

**Comment by salls** [comment]
No problem. Thanks for checking

**Pull request merged**
